---
- name: Download vault package
  get_url:
    url: https://releases.hashicorp.com/vault/0.6.2/vault_0.6.2_linux_amd64.zip
    dest: "{{ package_dest }}"
  ignore_errors: yes

- name: Installing unzip ...
  apt: name=unzip state=installed

- name: Recursively decompress GZ files in ApplicationLogs.zip
  unarchive:
    src: "{{ package_dest }}/vault_0.6.2_linux_amd64.zip"
    dest: "{{ vault_dest }}"
    remote_src: yes

- name: move valut into usr/local/bin directory
  command: mv "{{ vault_dest }}/vault"  /usr/local/bin

- name: run the testing environmet
  shell: vault server -dev &

- name: Update bashrc file.....
  lineinfile:
    path: ~/.bashrc
    line: export VAULT_ADDR="http://{{ vault_server_ip }}:8200"
    insertafter: EOF
  tags: bash

- name: Adding catalina configuration file ...
  template: src=vault.sh.j2 dest=/root/vault.sh mode=0755

- name: execute the script
  shell: bash /root/vault.sh
#- name: export vault address....
#  command: export VAULT_ADDR="http://{{ vault_server_ip }}:8200"

