---
- name: Download vault package
  get_url:
    url: https://releases.hashicorp.com/vault/0.9.3/vault_0.9.3_linux_amd64.zip
    dest: "{{ package_dest }}"
  ignore_errors: yes

- name: Installing unzip ...
  apt: name=unzip state=installed

- name: Recursively decompress GZ files in ApplicationLogs.zip
  unarchive:
    src: "{{ package_dest }}/vault_0.9.3_linux_amd64.zip"
    dest: "{{ vault_dest }}"
    remote_src: yes

- name: move valut into usr/local/bin directory
  command: mv "{{ vault_dest }}/vault"  /usr/local/bin

#- name: run the testing environmet
#  shell: vault server -dev &

- name: Update bashrc file.....
  lineinfile:
    path: ~/.bashrc
    line: export VAULT_ADDR="http://{{ vault_server_ip }}:8200"
    insertafter: EOF
  tags: bash

- name: Adding catalina configuration file ...
  template: src=vault.sh.j2 dest=/root/vault.sh mode=0755

- name: To create config directory
  file:
    path: /etc/vault.d/
    state: directory

- name: To copy config file
  template:
    src: config.hcl.j2
    dest: /etc/vault.d/config.hcl

- name: Adding catalina configuration file ...
  template: src=vault.service.j2 dest=/etc/systemd/system/vault.service 

- name: just force systemd to reread configs (2.4 and above)
  command: systemctl daemon-reload

- service:
    name: vault
    state: started

- name: execute the script
  shell: bash /root/vault.sh
  tags: bash

- name: Execute command vault init
  template: src=vault_init.sh.j2 dest=/root/vault_init.sh mode=0755
  tags:
    - red
